import os
import time
print("######       ####       #    #")
print("#    #       #   #       #   #")
print("#    #       #    #       ##")
print("#   ##       #   #         #")
print("#######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print(" ######       ####       #    #")
print(" #    #       #   #       #   #")
print(" #    #       #    #       ##")
print(" #   ##       #   #         #")
print(" #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("  ######       ####       #    #")
print("  #    #       #   #       #   #")
print("  #    #       #    #       ##")
print("  #   ##       #   #         #")
print("  #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("   ######       ####       #    #")
print("   #    #       #   #       #   #")
print("   #    #       #    #       ##")
print("   #   ##       #   #         #")
print("   #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("    ######       ####       #    #")
print("    #    #       #   #       #   #")
print("    #    #       #    #       ##")
print("    #   ##       #   #         #")
print("    #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("     ######       ####       #    #")
print("     #    #       #   #       #   #")
print("     #    #       #    #       ##")
print("     #   ##       #   #         #")
print("     #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("      ######       ####       #    #")
print("      #    #       #   #       #   #")
print("      #    #       #    #       ##")
print("      #   ##       #   #         #")
print("      #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("       ######       ####       #    #")
print("       #    #       #   #       #   #")
print("       #    #       #    #       ##")
print("       #   ##       #   #         #")
print("       #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("        ######       ####       #    #")
print("        #    #       #   #       #   #")
print("        #    #       #    #       ##")
print("        #   ##       #   #         #")
print("        #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("         ######       ####       #    #")
print("         #    #       #   #       #   #")
print("         #    #       #    #       ##")
print("         #   ##       #   #         #")
print("         #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("          ######       ####       #    #")
print("          #    #       #   #       #   #")
print("          #    #       #    #       ##")
print("          #   ##       #   #         #")
print("          #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("           ######       ####       #    #")
print("           #    #       #   #       #   #")         
print("           #    #       #    #       ##")
print("           #   ##       #   #         #")
print("           #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("            ######       ####       #    #")
print("            #    #       #   #       #   #")
print("            #    #       #    #       ##")
print("            #   ##       #   #         #")
print("            #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("             ######       ####       #    #")
print("             #    #       #   #       #   #")
print("             #    #       #    #       ##")
print("             #   ##       #   #         #")
print("             #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("              ######       ####       #    #")
print("              #    #       #   #       #   #")         
print("              #    #       #    #       ##")
print("              #   ##       #   #         #")
print("              #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("               ######       ####       #    #")
print("               #    #       #   #       #   #")
print("               #    #       #    #       ##")
print("               #   ##       #   #         #")
print("               #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("                ######       ####       #    #")
print("                #    #       #   #       #   #")
print("                #    #       #    #       ##")
print("                #   ##       #   #         #")
print("                #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("                 ######       ####       #    #")
print("                 #    #       #   #       #   #")
print("                 #    #       #    #       ##")
print("                 #   ##       #   #         #")
print("                 #######      ####          #")
time.sleep(0.1)
i = os.system('cls')
print("                  ######       ####       #    #")
print("                  #    #       #   #       #   #")
print("                  #    #       #    #       ##")
print("                  #   ##       #   #         #")
print("                  #######      ####          #")



        